### ISSUE TITLE
Works not on IE 10 & 11

### ISSUE THREAD

**Issue by stephan-fischer** [wieringen/tinycircleslider#6]
Hello,

the TinycircleSlider works not on IE 10 or 11. And it works not on Windows 8 Tablet. Can you may fix it? Is very important for IE user, because it is unusable.

Thanks! Best regards,
Stephan

**Comment by floreadm** [comment]
This is true.

This is not working on IE 10 and IE 11.
Any fix?

**Comment by floreadm** [comment]
@stephan-fischer, @wieringen 

Fix it.
On line 79.
Either you take out 
'onmsgesturechange' in window
from 
touchEvents = 'ontouchstart' in window || 'onmsgesturechange' in window
or

put this instead
touchEvents = !(window.navigator.userAgent.indexOf("MSIE ") > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)) && ('ontouchstart' in window || 'onmsgesturechange' in window)
